GroceryList_MVVM/Models/Category.cs
namespace GroceryList_MVVM.Models;

public class Category
{
    public int Id { get; set; }
    public string Name { get; set; }
    public List<Grocery> Groceries { get; set; }
}

GroceryList_MVVM/Models/ErrorViewModel.cs
namespace GroceryList_MVVM.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

GroceryList_MVVM/Models/Grocery.cs
 namespace GroceryList_MVVM.Models;

public class Grocery
{
    public int Id { get; set; }
    public string Name { get; set; }
    public string? Description { get; set; }
    public int Quantity { get; set; }
    public Category? Category { get; set; }
    public int CategoryId { get; set; }
}

GroceryList_MVVM/Controllers/GroceriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GroceryList_MVVM.Data;
using GroceryList_MVVM.Models;
using GroceryList_MVVM.Repository;

namespace GroceryList_MVVM.Controllers
{
    public class GroceriesController : Controller
    {
        private readonly IRepository<Grocery> _groceryRepository;
        private readonly IRepository<Category> _categoryRepository;

        public GroceriesController(IRepository<Grocery> groceryRepository, IRepository<Category> categoryRepository)
        {
            _groceryRepository = groceryRepository;
            _categoryRepository = categoryRepository;
        }

        // GET: Groceries
        public async Task<IActionResult> Index()
        {
            if (_groceryRepository == null)
            {
                return NotFound();
            }

            var groceries = await _groceryRepository.GetAll(includes: "Category");

            return View(groceries);
        }

        // GET: Groceries/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _groceryRepository == null)
            {
                return NotFound();
            }

            var grocery = await _groceryRepository.Get(grocery => grocery.Id == id, "Category" );

            if (grocery == null)
            {
                return NotFound();
            }

            return View(grocery);
        }

        // GET: Groceries/Create
        public async Task<IActionResult> Create()
        {
            ViewData["CategoryId"] = new SelectList(await _categoryRepository.GetAll(), nameof(Category.Id), nameof(Category.Name));
            return View();
        }

        // POST: Groceries/Create
        [HttpPost]
        public async Task<IActionResult> Create([Bind("Id,Name,Description,Quantity,CreatedAt,UpdatedAt,CategoryId")] Grocery grocery)
        {
            if (ModelState.IsValid)
            {
                await _groceryRepository.Add(grocery);
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoryId"] = new SelectList(await _categoryRepository.GetAll(), nameof(Category.Id), nameof(Category.Name));
            return View(grocery);
        }

        // GET: Groceries/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _groceryRepository == null)
            {
                return NotFound();
            }

            var grocery = await _groceryRepository.Get(grocery => grocery.Id == id, "Category");
            if (grocery == null)
            {
                return NotFound();
            }
            ViewData["CategoryId"] = new SelectList(await _categoryRepository.GetAll(), nameof(Category.Id), nameof(Category.Name));
            return View(grocery);
        }

        // POST: Groceries/Edit/5
        [HttpPost]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Description,Quantity,CreatedAt,UpdatedAt,CategoryId")] Grocery grocery)
        {
            if (id != grocery.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _groceryRepository.Update(grocery);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!await _groceryRepository.Exists(grocery => grocery.Id == id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }   
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoryId"] = new SelectList(await _categoryRepository.GetAll(), nameof(Category.Id), nameof(Category.Name));
            return View(grocery);
        }

        // GET: Groceries/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _groceryRepository == null)
            {
                return NotFound();
            }

            var grocery = await _groceryRepository.Get(grocery => grocery.Id == id, "Category");
            if (grocery == null)
            {
                return NotFound();
            }

            return View(grocery);
        }

        // POST: Groceries/Delete/5
        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_groceryRepository == null)
            {
                return Problem("Entity set 'GroceriesListContext.Groceries'  is null.");
            }
            var grocery = await _groceryRepository.Get(grocery => grocery.Id == id, "Category");
            if (grocery != null)
            {
                await _groceryRepository.Remove(grocery);
            }
            
            return RedirectToAction(nameof(Index));
        }
    }
}

GroceryList_MVVM/Controllers/HomeController.cs
using GroceryList_MVVM.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace GroceryList_MVVM.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

GroceryList_MVVM/Views/Groceries/Create.cshtml
@model GroceryList_MVVM.Models.Grocery

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Grocery</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Quantity" class="control-label"></label>
                <input asp-for="Quantity" class="form-control" />
                <span asp-validation-for="Quantity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CategoryId" class="control-label"></label>
                <select asp-for="CategoryId" class ="form-control" asp-items="ViewBag.CategoryId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

GroceryList_MVVM/Views/Groceries/Delete.cshtml
@model GroceryList_MVVM.Models.Grocery

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Grocery</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Quantity)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Category)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Category.Name)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

GroceryList_MVVM/Views/Groceries/Details.cshtml
@model GroceryList_MVVM.Models.Grocery

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Grocery</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Quantity)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Category)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Category.Name)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

GroceryList_MVVM/Views/Groceries/Edit.cshtml
@model GroceryList_MVVM.Models.Grocery

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Grocery</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Quantity" class="control-label"></label>
                <input asp-for="Quantity" class="form-control" />
                <span asp-validation-for="Quantity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Category" class="control-label"></label>
                <select asp-for="CategoryId" class="form-control" asp-items="ViewBag.CategoryId"></select>
                <span asp-validation-for="CategoryId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

GroceryList_MVVM/Views/Groceries/Index.cshtml
@model IEnumerable<GroceryList_MVVM.Models.Grocery>

@{
    ViewData["Title"] = "Index";
}

<div class="row justify-content-center">
    <div class="col-auto">
<h1 class="text-center text-primary">My Grocery List</h1>
        <p class="text-center">
            Add
            <a asp-action="Create"><i style="color:forestgreen;" class="bi bi-plus-square align-content-center"></i></a>
        </p>
    <table class="table table-responsive table-hover table-bordered">
        <thead class="table-dark">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Quantity)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Category)
            </th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Quantity)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Category.Name)
            </td>
            <td>
                <a asp-action="Details" asp-route-id="@item.Id"><i class="bi bi-eye"></i></a>
                <a asp-action="Edit" asp-route-id="@item.Id"><i style="color: goldenrod;" class="bi bi-pencil-square"></i></a>
                <a asp-action="Delete" asp-route-id="@item.Id"><i style="color:red;" class="bi bi-x-square"></i></a>
            </td>
        </tr>}
    </tbody>
</table>
</div>
</div>

GroceryList_MVVM/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4">My Grocery List Application</h1>
    <p class="lead">Simple CRUD application.</p>
  </div>
</div>

GroceryList_MVVM/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GroceryList_MVVM</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/GroceryList_MVVM.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">GroceryList</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Groceries" asp-action="Index">Grocery List</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - GroceryList by Tiago Silva</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>